export const actionTypes = {
    CREATE_TODO_ITEM: "CREATE_TODO_ITEM",
    DELETE_TODO_ITEM: "DELETE_TODO_ITEM",
    MARK_TODO_COMPLETED: "MARK_TODO_COMPLETED",

    LOAD_TODOS_IN_PROGRESS: "LOAD_TODOS_IN_PROGRESS",
    LOAD_TODOS_SUCCESS: "LOAD_TODOS_SUCCESS",
    LOAD_TODOS_FAILURE: "LOAD_TODOS_FAILURE",
};
